import {
  Car, Home, Utensils, Droplets, Recycle, ShoppingBag, Package,
  Bike, Snowflake, Leaf, Star,
  AlertTriangle, Flame, Skull,
  Sprout, Sword, Heart, TreeDeciduous, Sun,
  Zap, Bus, Wind,
  Trash2,
  Factory, CloudFog, Waves, ThermometerSun, Trees, Lightbulb, Briefcase,
  PenTool, Settings, BarChart2, Trophy, Fuel, Globe, Rocket,
  Newspaper, Search, RefreshCw, Beef, Calculator,
  Map, Flag, ClipboardList, Lock, TrendingUp, Medal, Calendar, MapPin,
  Share2, Users, Award, Coins, TrendingDown, ChevronDown, Check,
  User, Smartphone, Send, X,
  ArrowRight, AlertCircle, CheckCircle, LogOut, MessageSquare, Loader, Clock,
  BookOpen, Footprints, Shield, CalendarCheck,
} from 'lucide-react';

const iconMap = {
  'car': Car,
  'home': Home,
  'utensils': Utensils,
  'droplets': Droplets,
  'recycle': Recycle,
  'shopping-bag': ShoppingBag,
  'package': Package,
  'trash-2': Trash2,
  'newspaper': Newspaper,
  'beef': Beef,
  'search': Search,
  'refresh-cw': RefreshCw,
  'send': Send,
  'x': X,
  'calculator': Calculator,
  'map': Map,
  'map-pin': MapPin,
  'flag': Flag,
  'clipboard-list': ClipboardList,
  'lock': Lock,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'chevron-down': ChevronDown,
  'check': Check,
  'medal': Medal,
  'calendar': Calendar,
  'share-2': Share2,
  'users': Users,
  'award': Award,
  'coins': Coins,
  'user': User,
  'user-round': User,
  'user-circle-2': User,
  'contact': User,
  'smartphone': Smartphone,
  'bike': Bike,
  'snowflake': Snowflake,
  'leaf': Leaf,
  'star': Star,
  'alert-triangle': AlertTriangle,
  'flame': Flame,
  'skull': Skull,
  'sprout': Sprout,
  'sword': Sword,
  'heart': Heart,
  'tree-deciduous': TreeDeciduous,
  'sun': Sun,
  'zap': Zap,
  'bus': Bus,
  'wind': Wind,
  'factory': Factory,
  'cloud-fog': CloudFog,
  'waves': Waves,
  'thermometer-sun': ThermometerSun,
  'trees': Trees,
  'lightbulb': Lightbulb,
  'briefcase': Briefcase,
  'pen-tool': PenTool,
  'settings': Settings,
  'bar-chart-2': BarChart2,
  'trophy': Trophy,
  'fuel': Fuel,
  'globe': Globe,
  'rocket': Rocket,
  'arrow-right': ArrowRight,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle,
  'log-out': LogOut,
  'message-square': MessageSquare,
  'loader': Loader,
  'clock': Clock,
  'book-open': BookOpen,
  'footprints': Footprints,
  'shield': Shield,
  'calendar-check': CalendarCheck,
};

export default function Icon({ name, size = 24, color = 'currentColor', className = '', ariaLabel }) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return (
    <LucideIcon
      size={size}
      color={color}
      className={className}
      aria-hidden={ariaLabel ? undefined : true}
      aria-label={ariaLabel}
    />
  );
}
