import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import CountUpModule from 'react-countup';
import { useInView } from 'react-intersection-observer';
import useAuthStore from '../store/authStore';

const CountUp = CountUpModule.default || CountUpModule;

import Icon from '../components/shared/Icon';
import LiveScoreEngine from '../components/features/LiveScoreEngine';
import Earth3D from '../components/features/Earth3D';
import HeroAnimationOverlay from '../components/features/HeroAnimationOverlay';

/* ─── Data ─────────────────────────────────── */
const CARBON_CONCEPTS = [
  { icon: 'zap', title: 'Energy', desc: 'Power generation burns fossil fuels, releasing CO₂ with every kilowatt-hour consumed.', color: 'var(--warning)' },
  { icon: 'car', title: 'Travel', desc: 'Petrol and diesel vehicles emit CO₂ through combustion. Every 10km = ~2.1kg CO₂.', color: 'var(--secondary)' },
  { icon: 'trash-2', title: 'Waste', desc: 'Waste in landfills produces methane, a greenhouse gas 25 times more potent than CO₂.', color: 'var(--danger)' },
];

const CONCEPT_DETAILS = {
  Energy: {
    icon: 'zap',
    color: '#D97706',
    bg: '#FEF3C7',
    overview: 'Energy consumption in homes and offices is one of the largest sources of greenhouse gases. The electricity and heating we use daily are heavily generated by burning fossil fuels, releasing massive amounts of carbon dioxide (CO₂) into the atmosphere.',
    stats: [
      { value: '40%', label: 'Of global emissions come from power generation' },
      { value: '1 kg', label: 'Of CO₂ is released for every 1 kWh of coal power' },
    ],
    causes: [
      'Heating & cooling spaces (HVAC systems) account for over 50% of home energy consumption.',
      'Water heating is the second largest energy expense in typical households.',
      'Vampire power: plugged-in devices draw current continuously even when turned off.',
      'Inefficient appliances and traditional lightbulbs waste 90% of electricity as heat.'
    ],
    actions: [
      'Switch to LED lightbulbs — they use 75% less energy and last 25x longer.',
      'Unplug chargers, power strips, and appliances when not in use.',
      'Set your air conditioner to 24°C instead of lower settings.',
      'Invest in Energy Star certified appliances and rooftop solar panels.'
    ]
  },
  Travel: {
    icon: 'car',
    color: '#2563EB',
    bg: '#DBEAFE',
    overview: 'Transportation is a dominant source of emissions worldwide. Most passenger and cargo vehicles rely on internal combustion engines that burn petroleum-based fuels, releasing carbon dioxide, carbon monoxide, and air pollutants directly into our breathing space.',
    stats: [
      { value: '24%', label: 'Of global CO₂ emissions are caused by transportation' },
      { value: '4.6T', label: 'CO₂ emitted by an average passenger vehicle annually' },
    ],
    causes: [
      'Single-occupancy vehicle travel is the most carbon-intensive daily commute option.',
      'Aviation emissions: flying produces high-altitude emissions with a larger warming effect.',
      'Idling: running your car engine while stationary wastes fuel and releases pollutants.',
      'Low tire pressure reduces gas mileage and increases wear and emissions.'
    ],
    actions: [
      'Walk, cycle, or use public transport for short commutes (under 5km).',
      'Set up carpooling with colleagues or neighbors to reduce total trips.',
      'Maintain proper tire inflation and regular engine servicing to boost fuel economy.',
      'Consider switching to an electric vehicle (EV) or hybrid for your next car.'
    ]
  },
  Waste: {
    icon: 'trash-2',
    color: '#DC2626',
    bg: '#FEE2E2',
    overview: 'Waste disposal has a hidden, heavy impact on global warming. When organic waste (like food, paper, and garden debris) is buried in landfills, it decomposes under anaerobic (oxygen-starved) conditions, producing methane (CH₄) — a greenhouse gas far more potent than CO₂.',
    stats: [
      { value: '25x', label: 'Methane is 25 times more potent than carbon dioxide at trapping heat' },
      { value: '8%', label: 'Of global greenhouse gas emissions come from food waste alone' },
    ],
    causes: [
      'Food waste decomposing in landfills is the primary source of landfill methane.',
      'Single-use plastics release greenhouse gases as they degrade in sunlight and pollute oceans.',
      'Throwing away recyclables (paper, glass, metals) forces raw material harvesting, increasing energy use.'
    ],
    actions: [
      'Start composting food scraps and yard waste to eliminate landfill methane.',
      'Buy food mindfully, plan meals, and store leftovers to prevent food waste.',
      'Carry reusable water bottles, shopping bags, and avoid single-use packaging.',
      'Clean and separate your recyclables (metals, glass, clean paper/cardboard).'
    ]
  }
};

const IMPACTS = [
  { icon: 'cloud-fog', title: 'Air Pollution', desc: '7 million deaths annually from air pollution linked to fossil fuel burning.', stat: '7M deaths/yr' },
  { icon: 'waves', title: 'Ocean Damage', desc: 'Oceans absorb 30% of CO₂, causing acidification that kills coral reefs.', stat: '30% absorbed' },
  { icon: 'thermometer-sun', title: 'Rising Temps', desc: 'Global temperatures have risen 1.2°C since pre-industrial times, heading to 1.5°C.', stat: '+1.2°C rise' },
  { icon: 'trees', title: 'Deforestation', desc: '15 billion trees are cut down every year, removing critical carbon sinks.', stat: '15B trees/yr' },
];

const REDUCTION_TIPS = [
  { cat: 'Transport', icon: 'bus', tips: ['Use public transport daily', 'Switch to an electric vehicle', 'Carpool with colleagues', 'Cycle for trips under 5km', 'Work from home when possible', 'Take trains over planes', 'Walk for short distances', 'Service your vehicle regularly'] },
  { cat: 'Home Energy', icon: 'home', tips: ['Set AC to 24°C instead of 20°C', 'Switch to LED light bulbs', 'Use solar panels', 'Insulate your home properly', 'Unplug devices when idle', 'Use energy-efficient appliances', 'Reduce hot water usage', 'Air-dry clothes instead of dryer'] },
  { cat: 'Food', icon: 'leaf', tips: ['Eat one less meat meal per week', 'Choose local, seasonal produce', 'Reduce food waste', 'Grow your own vegetables', 'Compost food scraps', 'Buy organic when possible', 'Reduce dairy consumption', 'Choose plant-based alternatives'] },
  { cat: 'Waste', icon: 'recycle', tips: ['Carry a reusable water bottle', 'Bring your own shopping bags', 'Recycle properly', 'Buy second-hand items', 'Repair instead of replace', 'Avoid single-use packaging', 'Compost organic waste', 'Choose products with less packaging'] },
  { cat: 'Awareness', icon: 'lightbulb', tips: ['Track your carbon footprint daily', 'Educate friends and family', 'Support green businesses', 'Vote for climate policies', 'Plant trees in your area', 'Donate to environmental causes', 'Share eco tips on social media', 'Join local green groups'] },
  { cat: 'Work & Tech', icon: 'briefcase', tips: ['Use video calls instead of travel', 'Go paperless in the office', 'Choose green web hosting', 'Turn off monitors at night', 'Use rechargeable batteries', 'Purchase carbon offsets', 'Support renewable energy programs', 'Encourage green policies at work'] },
];

const HOW_STEPS = [
  { step: '01', icon: 'clipboard-list', title: 'Track', desc: 'Log your daily activities like driving, electricity use, meals, and purchases.' },
  { step: '02', icon: 'bar-chart-2', title: 'Analyze', desc: 'Our engine instantly calculates your exact carbon footprint and gives you a score.' },
  { step: '03', icon: 'lightbulb', title: 'Improve', desc: 'Get personalized AI suggestions and form eco-friendly habits.' },
  { step: '04', icon: 'trending-down', title: 'Reduce', desc: 'Lower your emissions over time and earn rewards for your progress.' },
];

const GLOBAL_STATS = [
  { value: 37.4, suffix: 'B', label: 'Tonnes CO₂ emitted in 2024', icon: 'wind', decimals: 1 },
  { value: 15, suffix: 'B', label: 'Trees cut down each year', icon: 'trees', decimals: 0 },
  { value: 8, suffix: 'M T', label: 'Plastic dumped in oceans yearly', icon: 'waves', decimals: 0 },
  { value: 80, suffix: '%', label: 'Of energy still from fossil fuels', icon: 'fuel', decimals: 0 },
];

/* ─── Components ────────────────────────────── */
function StatCounter({ value, suffix, label, icon, decimals }) {
  const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.3 });
  return (
    <motion.div
      ref={ref}
      className="glass-card"
      style={{ padding: '32px 24px', textAlign: 'center' }}
      whileHover={{ scale: 1.03 }}
    >
      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '8px', color: 'var(--primary)' }}>
        <Icon name={icon} size={40} />
      </div>
      <div className="text-stat gradient-text" style={{ marginBottom: '4px', lineHeight: 1, color: 'var(--text-primary)' }}>
        {inView ? <CountUp end={value} decimals={decimals} duration={2.5} separator="," /> : '0'}
        {suffix}
      </div>
      <div className="text-caption" style={{ marginTop: '8px', lineHeight: 1.4 }}>{label}</div>
    </motion.div>
  );
}

/* ─── Floating Particles ────────────────────── */
const HERO_PARTICLES = [...Array(18)].map((_, i) => ({
  left: `${Math.random() * 100}%`,
  top: `${100 + Math.random() * 20}%`,
  width: `${3 + Math.random() * 5}px`,
  height: `${3 + Math.random() * 5}px`,
  bg: i % 3 === 0 ? '#00C896' : i % 3 === 1 ? '#4ADE80' : 'rgba(0,200,150,0.4)',
  animateY: -(600 + Math.random() * 400),
  animateX: (Math.random() - 0.5) * 150,
  duration: 8 + Math.random() * 8,
  delay: Math.random() * 10,
}));

function Particles() {
  return (
    <div style={{ position: 'absolute', inset: 0, overflow: 'hidden', pointerEvents: 'none' }}>
      {HERO_PARTICLES.map((p, i) => (
        <motion.div
          key={i}
          style={{
            position: 'absolute',
            left: p.left,
            top: p.top,
            width: p.width,
            height: p.height,
            borderRadius: '50%',
            background: p.bg,
          }}
          animate={{
            y: [0, p.animateY],
            x: [0, p.animateX],
            opacity: [0, 1, 1, 0],
          }}
          transition={{
            duration: p.duration,
            repeat: Infinity,
            delay: p.delay,
            ease: 'easeOut',
          }}
        />
      ))}
    </div>
  );
}


/* ─── Footprint Background ─────────────────── */
function Footprint({ isLeft, style }) {
  const dx = isLeft ? -1 : 1;
  return (
    <svg
      width="36"
      height="72"
      viewBox="-20 -30 40 60"
      style={{
        position: 'absolute',
        fill: 'rgba(0, 200, 150, 0.12)',
        pointerEvents: 'none',
        ...style
      }}
    >
      {/* Heel */}
      <ellipse cx={dx * 2} cy={14} rx={6} ry={9} transform={`rotate(${dx * 4} ${dx * 2} 14)`} />
      {/* Sole */}
      <ellipse cx={dx * 1} cy={-2} rx={9} ry={13} transform={`rotate(${dx * 6} ${dx * 1} -2)`} />
      {/* Toes */}
      <circle cx={dx * 4} cy={-19} r={2.7} />
      <circle cx={dx * 10} cy={-17} r={2.3} />
      <circle cx={dx * 15} cy={-13} r={1.9} />
      <circle cx={dx * 18} cy={-7} r={1.5} />
      <circle cx={dx * -3} cy={-18} r={3.8} /> {/* Big toe */}
    </svg>
  );
}

function BackgroundFootprints() {
  const steps = [
    { left: '6%', top: '80%', rotate: 32, isLeft: true },
    { left: '12%', top: '72%', rotate: 28, isLeft: false },
    { left: '18%', top: '63%', rotate: 24, isLeft: true },
    { left: '25%', top: '56%', rotate: 18, isLeft: false },
    { left: '32%', top: '48%', rotate: 12, isLeft: true },
    { left: '40%', top: '42%', rotate: 6, isLeft: false },
    { left: '48%', top: '35%', rotate: -2, isLeft: true },
    { left: '57%', top: '29%', rotate: -10, isLeft: false },
    { left: '65%', top: '22%', rotate: -18, isLeft: true },
    { left: '74%', top: '16%', rotate: -24, isLeft: false },
    { left: '82%', top: '11%', rotate: -30, isLeft: true },
    { left: '90%', top: '6%', rotate: -36, isLeft: false },
  ];

  return (
    <div style={{ position: 'absolute', inset: 0, overflow: 'hidden', pointerEvents: 'none', zIndex: 1 }}>
      {steps.map((s, i) => (
        <Footprint
          key={i}
          isLeft={s.isLeft}
          style={{
            left: s.left,
            top: s.top,
            transform: `rotate(${s.rotate}deg)`,
            opacity: 0.12,
            filter: 'drop-shadow(0 0 8px rgba(0, 200, 150, 0.4))',
          }}
        />
      ))}
    </div>
  );
}

/* ─── Animated Quote ───────────────────────── */
function AnimatedQuote() {
  return (
    <div
      style={{
        position: 'absolute',
        top: '-40px',
        left: '35%',
        transform: 'translateX(-50%)',
        zIndex: 40,
        pointerEvents: 'none',
        display: 'flex',
        justifyContent: 'center'
      }}
    >
      <motion.div
        animate={{ y: [0, -10, 0] }}
        transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }}
        style={{
          position: 'relative',
          padding: '10px 20px 10px 14px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          borderRadius: '16px',
          background: 'rgba(255, 255, 255, 0.65)',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.8)',
          boxShadow: '0 20px 40px rgba(0, 200, 150, 0.08)',
          maxWidth: 'calc(100% - 32px)',
          boxSizing: 'border-box'
        }}
      >
        {/* Animated Glow Behind Icon */}
        <motion.div 
          animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.6, 0.3] }}
          transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
          style={{ position: 'absolute', left: '14px', top: '50%', marginTop: '-18px', width: '36px', height: '36px', background: 'var(--primary)', filter: 'blur(12px)', borderRadius: '50%', zIndex: -1 }}
        />
        
        {/* Floating Icon */}
        <div style={{
          width: '36px', height: '36px', borderRadius: '10px', background: 'linear-gradient(135deg, #ffffff 0%, #f0fdf4 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 6px 16px rgba(0, 200, 150, 0.12)', position: 'relative', flexShrink: 0
        }}>
          <Icon name="leaf" size={18} color="var(--primary)" />
        </div>

        {/* Text */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', minWidth: 0 }}>
          <motion.div
            initial={{ opacity: 0, x: -15 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 1 }}
            style={{ fontSize: 'clamp(0.58rem, 1.2vw, 0.65rem)', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1.5px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}
          >
            Unleash Your Power
          </motion.div>
          <motion.div
            initial={{ opacity: 0, x: -15 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 1.2 }}
            style={{ fontSize: 'clamp(0.95rem, 1.8vw, 1.15rem)', fontWeight: 900, color: 'var(--text-primary)', letterSpacing: '-0.3px', lineHeight: 1.2 }}
          >
            Be the Superhero <span style={{ background: 'linear-gradient(135deg, #00C896 0%, #059669 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', display: 'inline-block' }}>Our Planet Needs</span>.
          </motion.div>
        </div>
      </motion.div>
    </div>
  );
}

/* ─── Main Page ────────────────────────────── */
export default function Home() {
  const { isAuthenticated } = useAuthStore();
  const [expandedTips, setExpandedTips] = useState({});
  const [selectedConcept, setSelectedConcept] = useState(null);

  useEffect(() => {
    if (selectedConcept) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [selectedConcept]);

  const earthContainerRef = useRef(null);
  const humanContainerRef = useRef(null);
  const [animPhase, setAnimPhase] = useState(0);

  useEffect(() => {
    let timeout;
    const runLoop = (currentPhase) => {
      setAnimPhase(currentPhase);
      let duration = 0;
      if (currentPhase === 0) duration = 8000;      // Phase 0: Zoomed Earth & Hold (8.0s)
      else if (currentPhase === 1) duration = 4500; // Phase 1: Move to side & Human formation (4.5s)
      else if (currentPhase === 2) duration = 4500; // Phase 2: Flow from Human to Earth (4.5s)
      else if (currentPhase === 3) duration = 500;  // Phase 3: Quick reset (0.5s)

      timeout = setTimeout(() => {
        runLoop(currentPhase >= 3 ? 0 : currentPhase + 1);
      }, duration);
    };

    runLoop(0);

    return () => clearTimeout(timeout);
  }, []);

  /* Subtle hero scroll nudge on load / navigation to home */
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    const SCROLL_AMOUNT = 36;
    const html = document.documentElement;
    const originalScrollBehavior = html.style.scrollBehavior;
    const timers = [];

    timers.push(setTimeout(() => {
      html.style.scrollBehavior = 'smooth';
      window.scrollTo({ top: SCROLL_AMOUNT, behavior: 'smooth' });

      timers.push(setTimeout(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });

        timers.push(setTimeout(() => {
          html.style.scrollBehavior = originalScrollBehavior;
        }, 400));
      }, 500));
    }, 350));

    return () => {
      timers.forEach(clearTimeout);
      window.scrollTo({ top: 0, behavior: 'auto' });
      html.style.scrollBehavior = originalScrollBehavior;
    };
  }, []);


  const toggleTip = (index) => {
    setExpandedTips(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };
  return (
    <div>
      {/* ══════════════════════════════════════
          SECTION 1 — Hero
      ══════════════════════════════════════ */}
      <section
        className="hero-gradient"
        style={{
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
          paddingTop: 'clamp(80px, 6vw, 90px)',
          paddingBottom: 'clamp(40px, 6vw, 60px)',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Background glow */}
        <div style={{
          position: 'absolute',
          top: '20%',
          left: '50%',
          transform: 'translateX(-50%)',
          width: '600px',
          height: '600px',
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(0,200,150,0.12) 0%, transparent 65%)',
          pointerEvents: 'none',
        }} />

        <BackgroundFootprints />

        <Particles />

        <div
          style={{ margin: '0 auto', position: 'relative' }}
          className="container"
        >
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <div className="hero-left-col">
              <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7 }}
              >
              </motion.div>

              <motion.h1
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.1 }}
                className="text-hero"
                style={{ marginBottom: '16px' }}
              >
                Track Your Carbon.{' '}
                <span className="gradient-text">Save Your Planet.</span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.2 }}
                style={{ fontSize: '1.2rem', color: 'var(--text-muted)', maxWidth: '540px', lineHeight: 1.7, marginBottom: '24px' }}
              >
                EcoQuest helps you understand, track, and reduce your carbon footprint with real-time analytics, AI-powered suggestions, and a rewarding eco-journey.
              </motion.p>

               <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.3 }}
                style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}
              >
                <Link to={isAuthenticated ? '/tracker' : '/signup'} style={{ flex: '1 1 auto', minWidth: 'min(200px, 100%)' }}>
                  <motion.button className="btn-primary" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }} style={{ fontSize: 'clamp(0.9rem, 2.5vw, 1rem)', padding: '14px clamp(20px, 4vw, 32px)', width: '100%' }}>
                    <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}><Icon name="rocket" size={18} /> {isAuthenticated ? 'Go to Tracker' : 'Start Your Eco Journey'}</span>
                  </motion.button>
                </Link>
                <Link to="/calculator" style={{ flex: '1 1 auto', minWidth: 'min(160px, 100%)' }}>
                  <motion.button className="btn-outline" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }} style={{ fontSize: 'clamp(0.9rem, 2.5vw, 1rem)', padding: '14px clamp(20px, 4vw, 32px)', background: '#FFFFFF', width: '100%' }}>
                    Calculate Now
                  </motion.button>
                </Link>

              </motion.div>

              {/* Trust indicators */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.6 }}
                style={{ display: 'flex', gap: 'clamp(16px, 4vw, 32px)', marginTop: '36px', flexWrap: 'wrap' }}
              >
                {[['2.4M+', 'Active Users'], ['150+', 'Countries'], ['18K T', 'CO₂ Saved']].map(([val, lbl]) => (
                  <div key={lbl}>
                    <div className="hero-stat" style={{ fontSize: 'clamp(1.2rem, 4vw, 1.6rem)', color: 'var(--primary)' }}>{val}</div>
                    <div className="text-caption" style={{ marginTop: '2px' }}>{lbl}</div>
                  </div>
                ))}
              </motion.div>
            </div>

            {/* Right Column: Interactive 3D Earth & Particle System */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1 }}
              style={{ position: 'relative', width: 'clamp(500px, 45vw, 650px)', height: 'clamp(500px, 45vw, 650px)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
              className="hidden lg:flex"
            >
              {/* === Spacer representing the Human on the left === */}
              <motion.div
                ref={humanContainerRef}
                initial={{ width: 0, opacity: 0 }}
                animate={{
                  width: animPhase === 1 ? 'clamp(300px, 25vw, 400px)' : 0,
                  opacity: animPhase === 1 ? 1 : 0
                }}
                transition={{ duration: 1.5, ease: 'easeInOut' }}
                style={{ position: 'relative', flexShrink: 0, height: '90%' }}
              />

              <AnimatedQuote />

              <div
                ref={earthContainerRef}
                style={{
                  position: 'absolute',
                  top: '50%',
                  right: animPhase === 1 ? '100px' : '0',
                  transform: 'translateY(-50%)',
                  width: '100%',
                  height: '100%',
                  zIndex: 20,
                  touchAction: 'pan-y'
                }}
              >
                <Earth3D animPhase={animPhase} earthContainerRef={earthContainerRef} />
                <HeroAnimationOverlay
                  key="hero-overlay-v3"
                  phase={animPhase}
                  earthContainerRef={earthContainerRef}
                  humanContainerRef={humanContainerRef}
                />
              </div>
            </motion.div>
          </div>
        </div>

        {/* Scroll indicator */}
        <motion.div
          animate={{ y: [0, 10, 0], opacity: [0.5, 1, 0.5] }}
          transition={{ duration: 2, repeat: Infinity }}
          style={{ position: 'absolute', bottom: '32px', left: '50%', transform: 'translateX(-50%)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px' }}
        >
          <span style={{ color: 'rgba(0,200,150,0.6)', fontSize: '0.75rem', letterSpacing: '2px' }}>SCROLL</span>
          <div style={{ width: '1px', height: '40px', background: 'linear-gradient(to bottom, rgba(0,200,150,0.6), transparent)' }} />
        </motion.div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 2 — Carbon Explained
      ══════════════════════════════════════ */}
      <section className="section-padding" style={{ background: '#FFFFFF' }}>
        <div className="container">
          {/* Section Header — centred block */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{ textAlign: 'center', maxWidth: '640px', margin: '0 auto 48px' }}
          >
            <h2 className="section-title" style={{ marginBottom: '16px' }}>
              What is a <span className="gradient-text">Carbon Footprint?</span>
            </h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '1.05rem', lineHeight: 1.7, margin: 0 }}>
              A carbon footprint is the total greenhouse gas emissions caused by an individual,
              organization, or product — measured in tonnes of CO₂ equivalent.
            </p>
          </motion.div>

          {/* Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {CARBON_CONCEPTS.map((c, i) => (
              <motion.div
                key={c.title}
                data-aos="fade-up"
                data-aos-delay={i * 80}
                whileHover={{ scale: 1.04, y: -4, boxShadow: '0 20px 40px rgba(0,0,0,0.08)' }}
                whileTap={{ scale: 0.98 }}
                onClick={() => setSelectedConcept(c.title)}
                className="premium-card"
                style={{ padding: '28px', cursor: 'pointer', transition: 'box-shadow 0.3s ease' }}
              >
                <div style={{
                  width: '52px', height: '52px', borderRadius: '14px',
                  background: `${c.color}18`,
                  color: c.color,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  marginBottom: '18px',
                }}>
                  <Icon name={c.icon} size={28} />
                </div>
                <h3 className="text-card-title" style={{ marginBottom: '10px' }}>{c.title}</h3>
                <p className="text-body" style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '8px' }}>{c.desc}</p>
                {/* <div style={{ marginTop: '16px', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.82rem', color: c.color, fontWeight: 700 }}>
                  <span>Read detailed guide</span>
                  <Icon name="arrow-right" size={12} />
                </div> */}
              </motion.div>
            ))}
          </div>
        </div>
      </section>


      {/* ══════════════════════════════════════
          SECTION 3 — Human Impact (Left Image, Right Content)
      ══════════════════════════════════════ */}
      <section className="section-padding" style={{ background: 'var(--bg-dark)' }}>
        <div className="container">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center" data-aos="fade-up">

            {/* Left: Image / Illustration */}
            <motion.div
              data-aos="fade-right"
              style={{ 
                borderRadius: '24px', 
                background: 'linear-gradient(135deg, #FEE2E2, #F8FAFC)',
                border: '1px solid rgba(0,0,0,0.05)',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                gap: '24px',
                padding: '32px',
                boxShadow: '0 20px 40px rgba(0,0,0,0.03)'
              }}
            >
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                {[
                  { icon: 'factory', label: 'Factories' },
                  { icon: 'car', label: 'Vehicles' },
                  { icon: 'wind', label: 'Aviation' },
                  { icon: 'leaf', label: 'Agriculture' },
                ].map((item, i) => (
                  <div key={i} style={{ padding: '20px', background: '#FFFFFF', borderRadius: '16px', border: '1px solid rgba(0,0,0,0.05)', textAlign: 'center', boxShadow: '0 4px 10px rgba(0,0,0,0.02)' }}>
                    <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '8px', color: 'var(--danger)' }}><Icon name={item.icon} size={32} /></div>
                    <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', fontWeight: 500 }}>{item.label}</div>
                  </div>
                ))}
              </div>
              <div style={{ textAlign: 'center', padding: '24px', background: '#FFFFFF', borderRadius: '16px', border: '1px solid rgba(239,68,68,0.2)', boxShadow: '0 8px 20px rgba(239,68,68,0.08)' }}>
                <div style={{ fontSize: '3rem', fontWeight: 900, color: 'var(--danger)' }}>37.4B</div>
                <div style={{ color: 'var(--text-muted)', fontSize: '0.95rem', fontWeight: 500 }}>Tonnes of CO₂ emitted in 2024</div>
              </div>
            </motion.div>

            {/* Right: Content */}
            <div data-aos="fade-left">
              <h2 className="section-title" style={{ marginBottom: '20px' }}>
                The Human Impact on Our <span className="gradient-text">Planet</span>
              </h2>
              <p className="text-body" style={{ color: 'var(--text-muted)', marginBottom: '32px' }}>
                Human activities are pushing the planet to its limits. Climate change, pollution, and resource depletion are creating a crisis that demands immediate action from every one of us.
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                {IMPACTS.map((impact, i) => (
                  <motion.div
                    key={impact.title}
                    data-aos="fade-up"
                    data-aos-delay={i * 100}
                    className="premium-card"
                    style={{ padding: '20px', display: 'flex', gap: '16px', alignItems: 'flex-start' }}
                  >
                    <div style={{ flexShrink: 0, color: 'var(--danger)' }}><Icon name={impact.icon} size={32} /></div>
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
                        <h4 className="text-card-title">{impact.title}</h4>
                        <span className="badge badge-red" style={{ fontSize: '0.7rem', padding: '3px 10px' }}>{impact.stat}</span>
                      </div>
                      <p className="text-body" style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>{impact.desc}</p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 4 — Reduction Methods (2-Column Grid)
      ══════════════════════════════════════ */}
      <section className="section-padding" style={{ background: '#FFFFFF' }}>
        <div className="container">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ textAlign: 'center', marginBottom: '40px' }}>
            <h2 className="section-title" style={{ marginBottom: '16px' }}>
              How to <span className="gradient-text">Reduce Your Footprint</span>
            </h2>
            <p className="section-subtitle" style={{ margin: '0 auto' }}>
              Every small action adds up. Explore these proven methods to reduce your carbon emissions and live more sustainably.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {REDUCTION_TIPS.map((group, gi) => {
              const isOpen = expandedTips[gi];
              return (
                <motion.div
                  key={group.cat}
                  data-aos="fade-up"
                  data-aos-delay={gi * 80}
                  className="premium-card"
                  style={{
                    padding: '24px',
                    cursor: 'pointer',
                    border: isOpen ? '2px solid rgba(0, 200, 150, 0.4)' : '1px solid rgba(0, 0, 0, 0.05)',
                    background: isOpen ? 'rgba(0, 200, 150, 0.02)' : '#FFFFFF',
                    boxShadow: isOpen ? '0 12px 30px rgba(0, 200, 150, 0.08)' : '0 4px 15px rgba(0, 0, 0, 0.02)',
                    transition: 'all 0.3s ease'
                  }}
                  onClick={() => toggleTip(gi)}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: isOpen ? '16px' : '0', transition: 'margin 0.3s ease' }}>
                    <h3 className="text-card-title" style={{ display: 'flex', alignItems: 'center', gap: '12px', color: isOpen ? 'var(--primary)' : 'var(--text-primary)' }}>
                      <div style={{
                        padding: '8px',
                        borderRadius: '8px',
                        background: isOpen ? 'var(--primary)' : 'rgba(0, 200, 150, 0.1)',
                        color: isOpen ? '#FFFFFF' : 'var(--primary)',
                        display: 'flex',
                        transition: 'all 0.3s ease'
                      }}>
                        <Icon name={group.icon} size={20} />
                      </div>
                      {group.cat}
                    </h3>
                    <motion.div
                      animate={{ rotate: isOpen ? 180 : 0 }}
                      transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                      style={{
                        color: isOpen ? 'var(--primary)' : 'var(--text-muted)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        width: '32px',
                        height: '32px',
                        borderRadius: '50%',
                        background: isOpen ? 'rgba(0,200,150,0.1)' : 'transparent'
                      }}
                    >
                      <Icon name="chevron-down" size={20} />
                    </motion.div>
                  </div>
                  <AnimatePresence>
                    {isOpen && (
                      <motion.ul
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.3, ease: 'easeInOut' }}
                        style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '12px', overflow: 'hidden', paddingLeft: '4px' }}
                      >
                        {group.tips.map((tip, ti) => (
                          <motion.li
                            key={ti}
                            initial={{ opacity: 0, x: -10 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: ti * 0.04 }}
                            className="text-body"
                            style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', color: 'var(--text-secondary)', fontSize: '0.95rem' }}
                          >
                            <span style={{
                              background: 'var(--primary)',
                              color: '#fff',
                              borderRadius: '50%',
                              width: '18px',
                              height: '18px',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              fontSize: '10px',
                              flexShrink: 0,
                              marginTop: '3px',
                              boxShadow: '0 2px 5px rgba(0,200,150,0.3)'
                            }}>
                              <Icon name="check" size={12} />
                            </span>
                            {tip}
                          </motion.li>
                        ))}
                      </motion.ul>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 5 — How It Works (Timeline)
      ══════════════════════════════════════ */}
      <section className="section-padding" style={{ background: 'var(--bg-dark-100)' }}>
        <div className="container">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ textAlign: 'center', marginBottom: '50px' }}>
            <h2 className="section-title" style={{ marginBottom: '16px' }}>
              Your <span className="gradient-text">Journey to Zero</span>
            </h2>
            <p className="section-subtitle" style={{ margin: '0 auto' }}>
              A simple, continuous cycle to master your carbon footprint.
            </p>
          </motion.div>

          <div style={{ position: 'relative', maxWidth: '1000px', margin: '0 auto' }}>
            {/* Connecting line */}
            <div style={{
              position: 'absolute',
              top: '50px',
              left: '10%',
              right: '10%',
              height: '3px',
              background: 'linear-gradient(90deg, transparent, var(--primary), transparent)',
              zIndex: 0,
            }} className="hidden md:block" />

            <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              {HOW_STEPS.map((s, i) => (
                <motion.div
                  key={s.step}
                  data-aos="zoom-in"
                  data-aos-delay={i * 100}
                  style={{ textAlign: 'center', position: 'relative', zIndex: 1 }}
                >
                  <div style={{
                    width: '100px', height: '100px',
                    margin: '0 auto 24px',
                    background: '#FFFFFF',
                    borderRadius: '50%',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.06)',
                    border: '3px solid var(--primary)',
                    color: 'var(--primary)',
                    position: 'relative'
                  }}>
                    <Icon name={s.icon} size={40} />
                    <div style={{
                      position: 'absolute', top: '-10px', right: '-10px',
                      background: 'var(--primary)', color: '#FFFFFF',
                      width: '32px', height: '32px', borderRadius: '50%',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontWeight: 'bold', fontSize: '0.85rem', boxShadow: '0 4px 10px rgba(34,197,94,0.3)'
                    }}>
                      {i + 1}
                    </div>
                  </div>
                  <h3 className="text-card-title" style={{ marginBottom: '12px', fontSize: '1.2rem' }}>{s.title}</h3>
                  <p className="text-body" style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>{s.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 1.5 — Live Score Engine
      ══════════════════════════════════════ */}
      <section style={{ padding: '60px 0', background: 'var(--bg-dark)' }}>
        <div className="container">
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <LiveScoreEngine />
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 6 — Statistics
      ══════════════════════════════════════ */}
      <section className="section-padding" style={{ background: '#FFFFFF' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '60px' }} data-aos="fade-up">
            <h2 className="section-title" style={{ marginBottom: '16px' }}>
              The Numbers That <span className="gradient-text">Should Scare Us</span>
            </h2>
            <p className="section-subtitle" style={{ margin: '0 auto' }}>
              Real-time indicators showing the urgency of climate action across our planet.
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
            {GLOBAL_STATS.map((s, i) => (
              <div key={i} data-aos="zoom-in" data-aos-delay={i * 100}>
                <StatCounter {...s} />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════
          SECTION 7 — CTA
      ══════════════════════════════════════ */}
      <section style={{
        padding: 'clamp(60px, 10vw, 100px) 0',
        background: 'linear-gradient(135deg, #DCFCE7 0%, #D0F2FF 100%)',
        position: 'relative',
        overflow: 'hidden',
      }}>
        {/* Background glow */}
        <div style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: '800px',
          height: '400px',
          borderRadius: '50%',
          background: 'radial-gradient(ellipse, rgba(255,255,255,0.6) 0%, transparent 70%)',
          pointerEvents: 'none',
        }} />

        <div className="container" style={{ textAlign: 'center', position: 'relative' }}>
          <motion.div
            data-aos="zoom-in"
            whileInView={{ scale: [0.9, 1] }}
            transition={{ duration: 0.5 }}
          >
            <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '16px', color: 'var(--primary)' }}><Icon name="sprout" size={64} /></div>
            <h2 className="section-title" style={{ marginBottom: '20px', fontSize: 'clamp(2rem, 5vw, 3.5rem)', color: 'var(--text-primary)' }}>
              Start Reducing Your Footprint <span className="gradient-text">Today</span>
            </h2>
            <p className="text-body" style={{ color: 'var(--text-secondary)', fontSize: '1.1rem', maxWidth: '560px', margin: '0 auto 40px', lineHeight: 1.7 }}>
              Join 2.4 million eco-warriors already on their journey. Track, learn, reduce, and become a Climate Hero.
            </p>
            <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', flexWrap: 'wrap' }}>
              <Link to={isAuthenticated ? '/tracker' : '/signup'} style={{ flex: '1 1 auto', maxWidth: '240px' }}>
                <motion.button
                  className="btn-primary"
                  whileHover={{ scale: 1.06 }}
                  whileTap={{ scale: 0.97 }}
                  style={{ fontSize: 'clamp(0.95rem, 2.5vw, 1.05rem)', padding: '16px clamp(24px, 4vw, 40px)', width: '100%' }}
                >
                  <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}><Icon name="rocket" size={18} /> {isAuthenticated ? 'Go to Tracker' : 'Join EcoQuest Free'}</span>
                </motion.button>
              </Link>
              <Link to="/calculator" style={{ flex: '1 1 auto', maxWidth: '240px' }}>
                <motion.button
                  className="btn-outline"
                  whileHover={{ scale: 1.06 }}
                  whileTap={{ scale: 0.97 }}
                  style={{ fontSize: 'clamp(0.95rem, 2.5vw, 1.05rem)', padding: '16px clamp(24px, 4vw, 40px)', background: '#FFFFFF', width: '100%' }}
                >
                  Calculate My Carbon &rarr;
                </motion.button>
              </Link>
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginTop: '24px' }}>
              100% Free • No credit card required • Cancel anytime
            </p>
          </motion.div>
        </div>
      </section>

      {/* Dynamic Awareness Modal for Energy, Travel, and Waste */}
      <AnimatePresence>
        {selectedConcept && createPortal(
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={{
              position: 'fixed',
              inset: 0,
              zIndex: 1000,
              background: 'rgba(10, 15, 13, 0.82)',
              backdropFilter: 'blur(12px)',
              WebkitBackdropFilter: 'blur(12px)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '24px',
            }}
            onClick={() => setSelectedConcept(null)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ type: 'spring', stiffness: 320, damping: 26 }}
              onClick={e => e.stopPropagation()}
              style={{
                width: '100%',
                maxWidth: '600px',
                background: '#FFFFFF',
                borderRadius: '24px',
                padding: 'clamp(20px, 4vw, 36px)',
                boxShadow: '0 25px 60px rgba(0,0,0,0.35)',
                border: '1.5px solid rgba(0,0,0,0.05)',
                overflowY: 'auto',
                maxHeight: '90vh',
                boxSizing: 'border-box'
              }}
            >
              {/* Header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '20px' }}>
                <div style={{
                  width: '56px',
                  height: '56px',
                  borderRadius: '16px',
                  background: `${CONCEPT_DETAILS[selectedConcept].color}16`,
                  color: CONCEPT_DETAILS[selectedConcept].color,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0
                }}>
                  <Icon name={CONCEPT_DETAILS[selectedConcept].icon} size={30} />
                </div>
                <div>
                  <div style={{ fontSize: '0.75rem', fontWeight: 800, color: CONCEPT_DETAILS[selectedConcept].color, letterSpacing: '1.5px', textTransform: 'uppercase', marginBottom: '2px' }}>Carbon Awareness Guide</div>
                  <h2 style={{ fontSize: '1.6rem', fontWeight: 900, color: 'var(--text-primary)', margin: 0, letterSpacing: '-0.5px' }}>{selectedConcept} Footprint</h2>
                </div>
              </div>

              {/* Overview */}
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.98rem', lineHeight: 1.6, margin: '0 0 24px', background: 'rgba(0,0,0,0.02)', padding: '16px', borderRadius: '16px', borderLeft: `4px solid ${CONCEPT_DETAILS[selectedConcept].color}` }}>
                {CONCEPT_DETAILS[selectedConcept].overview}
              </p>

              {/* Stats Grid */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '24px' }}>
                {CONCEPT_DETAILS[selectedConcept].stats.map((st, si) => (
                  <div key={si} style={{ padding: '16px', borderRadius: '16px', background: `${CONCEPT_DETAILS[selectedConcept].color}08`, border: `1px solid ${CONCEPT_DETAILS[selectedConcept].color}18`, textAlign: 'center' }}>
                    <div style={{ fontSize: '1.8rem', fontWeight: 900, color: CONCEPT_DETAILS[selectedConcept].color, lineHeight: 1.1 }}>{st.value}</div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '4px', fontWeight: 500, lineHeight: 1.3 }}>{st.label}</div>
                  </div>
                ))}
              </div>

              {/* Why it Matters */}
              <div style={{ marginBottom: '24px' }}>
                <h4 style={{ fontSize: '0.88rem', color: 'var(--text-primary)', fontWeight: 800, letterSpacing: '0.5px', textTransform: 'uppercase', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <Icon name="alert-circle" size={14} color="var(--danger)" /> Why it Matters
                </h4>
                <ul style={{ padding: 0, margin: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {CONCEPT_DETAILS[selectedConcept].causes.map((cause, ci) => (
                    <li key={ci} style={{ display: 'flex', gap: '10px', fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                      <span style={{ color: 'var(--danger)', fontWeight: 'bold' }}>•</span>
                      <span>{cause}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Action Tips */}
              <div style={{ marginBottom: '28px' }}>
                <h4 style={{ fontSize: '0.88rem', color: 'var(--text-primary)', fontWeight: 800, letterSpacing: '0.5px', textTransform: 'uppercase', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <Icon name="check-circle" size={14} color="var(--primary)" /> How You Can Help
                </h4>
                <ul style={{ padding: 0, margin: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {CONCEPT_DETAILS[selectedConcept].actions.map((act, ai) => (
                    <li key={ai} style={{ display: 'flex', gap: '10px', fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                      <span style={{ color: 'var(--primary)', fontWeight: 'bold' }}>✓</span>
                      <span>{act}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Close Action */}
              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <motion.button
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => setSelectedConcept(null)}
                  style={{
                    padding: '12px 28px',
                    borderRadius: '12px',
                    border: 'none',
                    background: CONCEPT_DETAILS[selectedConcept].color,
                    color: '#FFFFFF',
                    fontWeight: 700,
                    fontSize: '0.9rem',
                    cursor: 'pointer',
                    boxShadow: `0 4px 14px ${CONCEPT_DETAILS[selectedConcept].color}40`,
                  }}
                >
                  Got it, thank you!
                </motion.button>
              </div>
            </motion.div>
          </motion.div>,
          document.body
        )}
      </AnimatePresence>

    </div>
  );
}
